version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: logartdb
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongo", "--username", "${MONGO_INITDB_ROOT_USERNAME}", "--password", "${MONGO_INITDB_ROOT_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "27017:27017"
    restart: unless-stopped

  app:
    image: davidmorenoo/logartapp:latest18
    ports:
      - "443:443"
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:443/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    env_file:
      - .env
